-- CreateTable
CREATE TABLE `Seat` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `airplaneId` INTEGER NOT NULL,
    `row` INTEGER NOT NULL,
    `col` INTEGER NOT NULL,
    `type` ENUM('BUSINESS', 'ECONOMY', 'PREMIUM_ECONOMY', 'FIRST_CLASS') NOT NULL DEFAULT 'ECONOMY',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Seat` ADD CONSTRAINT `Seat_airplaneId_fkey` FOREIGN KEY (`airplaneId`) REFERENCES `airplane`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
