-- CreateTable
CREATE TABLE `Bookings` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `flightId` INTEGER NOT NULL,
    `userId` INTEGER NOT NULL,
    `status` ENUM('BOOKED', 'CANCELLED', 'INITIATED', 'PENDING') NOT NULL DEFAULT 'INITIATED',
    `noOfSeats` INTEGER NOT NULL DEFAULT 1,
    `totalCost` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
